@extends('layouts.web')

@section('content')
<section class="textdivider">
    <div class="container text-center mt20">
        <h1 class="black">Are you a Institutional Investor?</h1>

        <h3><strong>Please read before answering</strong></h3>
        <p class="black font16">A qualified institutional buyer (QIB), in United States law and finance, is a purchaser of securities that is deemed financially sophisticated and is legally recognized by securities market regulators to need less protection from issuers than most public investors. Typically, the qualifications for this designation are based on an investor's total assets under management and specific legal conditions in the country where the fund is located. Rule 144A requires an institution to manage at least $100 million in securities from issuers not affiliated with the institution to be considered a QIB. If the institution is a bank or savings and loans thrift they must have a net worth of at least $25 million. If the institution is a registered dealer acting for its own account it must in the aggregate own and invest on a discretionary basis at least $10 million of securities of issuers not affiliated with the dealer.</p>
        <p class="black font16">The U.S. Securities and Exchange Commission (SEC) requires that an entity meet one of the following requirements to qualify as a QIB: Any of the following entities, acting for its own account or the accounts of other QIBs, that in the aggregate owns and invests on a discretionary basis at least $100 million in securities of issuers that are not affiliated with the entity: An insurance company An investment company registered under the Investment Company Act of 1940 A Small Business Investment Company licensed by the US Small Business Administration under the Small Business Investment Act of 1958 A plan established and maintained by a state, its political subdivisions, or state agency, for the benefit of its employees An employee benefit plan falling under the Employee Retirement Income Security Act of 1974 A trust fund whose trustee is a bank or trust company and whose participants are exclusively plans established for the benefit of state employees or employee benefit plans, except trust funds that include as participants individual retirement accounts or H.R. 10 plans A business development company as defined in section 202(a)(22) of the Investment Advisers Act of 1940. A 501(c)(3) charitable organization, corporation (other than a bank or a savings and loan association), partnership, or Massachusetts or similar business trust; and An investment adviser registered under the Investment Advisers Act of 1940. Any registered dealer, acting for its own account or the accounts of other QIBs, that in the aggregate owns and invests on a discretionary basis at least $10 million of securities of issuers that are not affiliated with the dealer. Any registered dealer acting in a riskless principal transaction on behalf of a qualified institutional buyer. Any investment company registered under the Investment Company Act, acting for its own account or for the accounts of other QIBs, that is part of a family of investment companies which own in the aggregate at least $100 million in securities of issuers, other than issuers that are affiliated with the investment company or are part of such family of investment companies. Any entity, all of the equity owners of which are QIBs, acting for its own account or the accounts of other QIBs. Any bank or any savings and loan association or other institution, acting for its own account or the accounts of other QIBs, that in the aggregate owns and invests on a discretionary basis at least $100 million in securities of issuers that are not affiliated with it and that has an audited net worth of at least $25 million as demonstrated in its latest annual financial statements, as of a date not more than 16 months preceding the date of sale under Rule 144A in the case of a US bank or savings and loan association, and not more than 18 months preceding the date of sale for a foreign bank or savings and loan association or equivalent institution</p>

    </div>
    <div class="container text-center">
        <a href="{{ url('login-investor')}}" class="btn btn-lg btn-primary btn-rounded font-weight-semibold px-5 btn-py-2 text-2">YES</a>
        <a href="{{ url('reject-login')}}" class="btn btn-lg btn-default btn-rounded font-weight-semibold px-5 btn-py-2 text-2">NO</a>
    </div>
    <div class="m-5"></div>
</section>
@endsection
